name: crypton
description: A simple Dart library for asymmetric encryption and digital signatures
version: 1.0.6
homepage: https://github.com/konstantinullrich
repository: https://github.com/konstantinullrich/crypton
issue_tracker: https://github.com/konstantinullrich/crypton/issues

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  pointycastle: ^1.0.2
  asn1lib: ^0.6.0

dev_dependencies:
  test: ^1.6.0
